#!/bin/bash
if [ $# -lt 1 ]
then
  echo "usage: $0 interface.method [arguments]"
  exit 1
fi

DEST=org.acpi.wakeup
OBJECT=/Wakeup
INTERFACE=$1
shift
echo dbus-send --system --type=method_call --dest=$DEST --print-reply $OBJECT $DEST.$INTERFACE "$@"

dbus-send --system --type=method_call --dest=$DEST --print-reply $OBJECT $DEST.$INTERFACE "$@"
